apiVersion: v1
kind: Service
metadata:
  name: two-tier-app
  namespace: production
spec:
  selector:
    app: two-tier-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
